<template>
  <div class="about">
    <h1>This is an about page</h1>
    Custom Element injected !!:
    <my-component first="web component generated by Stencil !" last="'Don't call me a framework' JS">ddd</my-component>
  </div>
</template>
